title: Henry Joseph Dugue Personal GitHub Pages Site
theme: jekyll-theme-minimal
description: Revelant Coursework:
Discrete Structures, Data Structures, Calculus, Linear Algebra, Statistics and Probability.

